heat_template_version: 2013-05-23
description: Meghdoot Test App
parameters:
  Pool_Name:
    type: string
    label: Floating IP Pool
    description: Floating IP Pool Range from which the instance will get assigned
  SSH_Key:
    type: string
    label: SSH Key
    description: Public key from the machine from which you'd like to access the instance
  Image_Name:
    type: string
    label: Image Name or ID
    description: An Ubuntu Cloud Image image already uploaded to OpenStack
resources:
  mango_flavor:
    type: OS::Nova::Flavor
    properties:
      ram: 2048
      vcpus: 1
      disk: 5
  mango_keypair:
    type: OS::Nova::KeyPair
    properties:
      name: mango_from_box1
      public_key: { get_param: SSH_Key }
  mango_instance:
    type: OS::Nova::Server
    depends_on: [ mango_flavor, mango_keypair ]
    properties:
      name: meghdoot_instance
      flavor: { get_resource: mango_flavor }
      image: { get_param: Image_Name }
      key_name: { get_resource: mango_keypair }
      user_data: |
        #!/bin/sh
        mkdir /home/ubuntu/HeatWasHere
  mango_floatingip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: Pool_Name }
  mango_ip_assoc:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: mango_floatingip }
      server_id: { get_resource: mango_instance }
      
